/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;
import View.Restaurant;
import java.awt.List;
import java.awt.event.ActionListener;
import java.awt.event.WindowEvent;
import javax.swing.JButton;
import javax.swing.JLabel;

import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author lavin
 */
public class Restaurant extends javax.swing.JFrame {

    /**
     * Creates new form Restaurant
     */
    public Restaurant() {
        initComponents();
    }
    
    public JTextField getNume() {
        return this.nume;
    }

    public JTextField getTel() {
        return this.tel;
    }

    public JTextField getAdresa() {
        return this.adresa;
    }

    public JTextField getComanda() {
        return this.cmd;
    }

    

    public void resetareJTextField(JTextField t) {
        t.setText("");
    }

    public JButton getAdaugareButon() {
        return this.adaugare;
    }
    
     public JButton getVizualizareButon() {
        return this.vizualizare;
    }

    

    public JButton getStergereButon() {
        return this.stergere;
    }

    

    public List getLista() {
        return this.listacomanda;
    }

    public void EvenimentButon(ActionListener ascultaButon) {
        adaugare.addActionListener(ascultaButon);
        vizualizare.addActionListener(ascultaButon);
        stergere.addActionListener(ascultaButon);
    }

    public void afiseazaMesaj(String mesaj) {
        JOptionPane.showMessageDialog(this, mesaj);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        nume = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tel = new javax.swing.JTextField();
        adresa = new javax.swing.JTextField();
        jbtnMeniu = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cmd = new javax.swing.JTextField();
        adaugare = new javax.swing.JButton();
        jbtnExit = new javax.swing.JButton();
        stergere = new javax.swing.JButton();
        vizualizare = new javax.swing.JButton();
        listacomanda = new java.awt.List();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 51, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel1.setText("SISTEM COMANDA ONLINE MANCARE");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, 597, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("NUME COMPLET CLIENT");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        nume.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numeActionPerformed(evt);
            }
        });
        getContentPane().add(nume, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 70, 138, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("TELEFON");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("ADRESA");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, -1));
        getContentPane().add(tel, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 110, 138, -1));
        getContentPane().add(adresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 150, 138, -1));

        jbtnMeniu.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbtnMeniu.setText("MENIU");
        jbtnMeniu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnMeniuActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnMeniu, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 400, 179, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("ADRESA");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("ADRESA");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("COMANDA");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));

        cmd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdActionPerformed(evt);
            }
        });
        getContentPane().add(cmd, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 200, 230, 60));

        adaugare.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        adaugare.setText("ADAUGARE COMANDA");
        getContentPane().add(adaugare, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 260, -1));

        jbtnExit.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbtnExit.setText("IESIRE");
        jbtnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnExitActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 400, -1, -1));

        stergere.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        stergere.setText("STERGERE");
        getContentPane().add(stergere, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 330, -1, -1));

        vizualizare.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        vizualizare.setText("VIZUALIZARE COMANDA");
        getContentPane().add(vizualizare, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 330, -1, -1));

        listacomanda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listacomandaActionPerformed(evt);
            }
        });
        getContentPane().add(listacomanda, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 60, 270, 210));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnMeniuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnMeniuActionPerformed
        Meniu Info = new Meniu();
        Info.setVisible(true);
    }//GEN-LAST:event_jbtnMeniuActionPerformed

    private void numeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numeActionPerformed

    private void cmdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmdActionPerformed

    private void jbtnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jbtnExitActionPerformed

    private void listacomandaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listacomandaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_listacomandaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Restaurant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Restaurant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Restaurant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Restaurant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Restaurant().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adaugare;
    private javax.swing.JTextField adresa;
    private javax.swing.JTextField cmd;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JButton jbtnExit;
    private javax.swing.JButton jbtnMeniu;
    private java.awt.List listacomanda;
    private javax.swing.JTextField nume;
    private javax.swing.JButton stergere;
    private javax.swing.JTextField tel;
    private javax.swing.JButton vizualizare;
    // End of variables declaration//GEN-END:variables

private void systemExit()
    {
        WindowEvent winClosing = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
    }
}
